### ISSUE TITLE
Initial image size

### ISSUE THREAD

**Issue by achaiah** [Lextal/pspnet-pytorch#4]
Hi,

Could you tell me what initial image size you are feeding into your PSPNet?

Thanks

**Comment by Lextal** [comment]
It's fully convolutional, the only requirement for an image is that it must be divisible by 8.

**Comment by achaiah** [comment]
Hi, I thought so too, but it does not seem to work. If I pass in a 512x512 image I get: `RuntimeError: Need input.size[1] == 2048 but got 512 instead.`  So something isn't completely right. Would you have any ideas?

Thanks

**Comment by Tshzzz** [comment]
Useing resnet50 is ok.

**Comment by Lextal** [comment]
It was due to the incorrect initialization of extractors. Fixed.

**Comment by achaiah** [comment]
Hey thanks for fixing it!  I can confirm that it now loads with resnet, however, it does not train. My loss never changes. I have many other models that train just fine with the same code so it looks like the issue is somewhere within the model. Any ideas?

Thanks

**Comment by mario98** [comment]
I'm still getting the error message "Need input.size[1] == 1024 but got 2048 instead." for resnet101. I'm using my own training code though, I just used models.  Image size is (768, 384).
